const express = require('express');
const app = express();
const candidateRoutes = require('./routes/candidates.routes');
const memberRoutes = require('./routes/members.routes');
const feeRoutes = require('./routes/fees.routes');
const companyRoutes = require('./routes/companies.routes');
const workerRequestRoutes = require('./routes/worker_requests.routes');
const biographyRoutes = require('./routes/biographies.routes');
const cityRoutes = require('./routes/cities.routes');
const municipalityRoutes = require('./routes/municipalities.routes');
const addressRoutes = require('./routes/addresses.routes');
const workerStructureRoutes = require('./routes/worker_structures.routes');
const institutionRoutes = require('./routes/educational_institutions.routes');
const educationRoutes = require('./routes/educations.routes');
const foreignLangRoutes = require('./routes/foreign_languages.routes');
const langSkillRoutes = require('./routes/language_skills.routes');
const parentRoutes = require('./routes/parents.routes');
const consentRoutes = require('./routes/consents.routes');
const idCardRoutes = require('./routes/id_cards.routes');
const healthCardRoutes = require('./routes/health_cards.routes');
const authorizedPersonRoutes = require('./routes/authorized_persons.routes');
const declarationRoutes = require('./routes/declarations.routes');
const contractRoutes = require('./routes/general_contracts.routes');
const workExpRoutes = require('./routes/work_experiences.routes');
const accessRequestRoutes = require('./routes/access_requests.routes');
const employeeRoutes = require('./routes/employees.routes');
const authRoutes = require('./routes/auth.routes');
const { verifyToken } = require('./middleware/auth.middleware');
const cors = require('cors');

app.use(express.json());
app.use(cors());
app.use('/api/auth', authRoutes);

app.use('/api/candidates', verifyToken, candidateRoutes);
app.use('/api/members', verifyToken, memberRoutes);
app.use('/api/fees', verifyToken, feeRoutes);
app.use('/api/companies', verifyToken, companyRoutes);
app.use('/api/worker-requests', verifyToken, workerRequestRoutes);
app.use('/api/biographies', verifyToken, biographyRoutes);
app.use('/api/cities', verifyToken, cityRoutes);
app.use('/api/municipalities', verifyToken, municipalityRoutes);
app.use('/api/addresses', verifyToken, addressRoutes);
app.use('/api/worker-structures', verifyToken, workerStructureRoutes);
app.use('/api/institutions', verifyToken, institutionRoutes);
app.use('/api/educations', verifyToken, educationRoutes);
app.use('/api/languages', verifyToken, foreignLangRoutes);
app.use('/api/language-skills', verifyToken, langSkillRoutes);
app.use('/api/parents', verifyToken, parentRoutes);
app.use('/api/consents', verifyToken, consentRoutes);
app.use('/api/id-cards', verifyToken, idCardRoutes);
app.use('/api/health-cards', verifyToken, healthCardRoutes);
app.use('/api/authorized-persons', verifyToken, authorizedPersonRoutes);
app.use('/api/declarations', verifyToken, declarationRoutes);
app.use('/api/contracts', verifyToken, contractRoutes);
app.use('/api/work-experiences', verifyToken, workExpRoutes);
app.use('/api/access-requests', verifyToken, accessRequestRoutes);
app.use('/api/employees', verifyToken, employeeRoutes);

module.exports = app;
